# Arquivo de configuração de tema do Streamlit

[theme]
# Cor principal usada para os widgets interativos (botões, sliders, etc.)
primaryColor="#1E88E5"  # Um azul mais vivo

# Cor de fundo da área principal do conteúdo
backgroundColor="#7fccf8" # Um cinza bem claro

# Cor de fundo da barra lateral (se você usar uma)
secondaryBackgroundColor="#FFFFFF" # Branco

# Cor do texto principal
textColor="#5a6164" # Um preto suave

# Fonte a ser usada. Pode ser "sans serif", "serif", ou "monospace".
# Para fontes customizadas, o método CSS (Opção 3) é necessário.
font="sans serif"